import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import i18n from "../i18n/config";

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "th", name: "Thai", nativeName: "ไทย", flag: "🇹🇭" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", flag: "🇸🇪" },
];

// Translation keys for the entire site
export type TranslationKey = 
  | "nav.shop" | "nav.men" | "nav.women" | "nav.trending" | "nav.accessories"
  | "hero.title1" | "hero.title2" | "hero.title3" | "hero.description"
  | "hero.explore" | "hero.lookbook" | "hero.trending" | "hero.views"
  | "categories.browse" | "categories.title" | "categories.products"
  | "products.featured" | "products.title" | "products.viewAll" | "products.addToCart"
  | "newsletter.title" | "newsletter.description" | "newsletter.placeholder" | "newsletter.subscribe"
  | "footer.description" | "footer.shop" | "footer.company" | "footer.support" | "footer.legal"
  | "footer.newArrivals" | "footer.bestsellers" | "footer.sale" | "footer.collections"
  | "footer.aboutUs" | "footer.careers" | "footer.press" | "footer.sustainability"
  | "footer.helpCenter" | "footer.shipping" | "footer.returns" | "footer.sizeGuide"
  | "footer.privacy" | "footer.terms" | "footer.cookies"
  | "footer.rights" | "footer.language"
  | "cart.title" | "cart.empty" | "cart.total" | "cart.checkout"
  | "wishlist.title" | "wishlist.empty"
  | "common.search" | "common.loading" | "common.new" | "common.sale"
  // Categories
  | "category.men" | "category.women" | "category.accessories"
  // Subcategories
  | "subcategory.tshirts" | "subcategory.shirts" | "subcategory.jeans" | "subcategory.trousers"
  | "subcategory.jackets" | "subcategory.hoodies" | "subcategory.shoes" | "subcategory.ethnicWear"
  | "subcategory.tops" | "subcategory.dresses" | "subcategory.skirts"
  | "subcategory.bags" | "subcategory.watches" | "subcategory.eyewear" | "subcategory.belts" | "subcategory.wallets" | "subcategory.jewelry"
  // Product types
  | "product.roundNeck" | "product.vNeck" | "product.polo" | "product.henley" | "product.graphic" | "product.striped" | "product.solid" | "product.printed"
  | "product.oxford" | "product.denim" | "product.linen" | "product.flannel" | "product.formal" | "product.casual"
  | "product.slimFit" | "product.skinny" | "product.straight" | "product.relaxed" | "product.ripped"
  | "product.chinos" | "product.cargo" | "product.joggers"
  | "product.bomber" | "product.leather" | "product.puffer"
  | "product.pullover" | "product.zipUp" | "product.fleece"
  | "product.sneakers" | "product.runningShoes" | "product.formalShoes" | "product.loafers" | "product.boots"
  | "product.kurta" | "product.sherwani" | "product.nehruJacket"
  | "product.cropTop" | "product.blouse" | "product.tankTop" | "product.peplumTop" | "product.wrapTop" | "product.ruffleTop"
  | "product.maxiDress" | "product.midiDress" | "product.bodycon" | "product.aLineDress" | "product.wrapDress" | "product.partyDress"
  | "product.momJeans" | "product.boyfriendJeans" | "product.wideLeg"
  | "product.palazzo" | "product.culottes" | "product.cigarettePants"
  | "product.pleatedSkirt" | "product.pencilSkirt" | "product.aLineSkirt"
  | "product.denimJacket" | "product.blazer"
  | "product.heels" | "product.sandals" | "product.flats"
  | "product.saree" | "product.lehenga" | "product.kurti"
  | "product.backpack" | "product.toteBag" | "product.slingBag" | "product.duffleBag"
  | "product.analogWatch" | "product.smartWatch" | "product.chronograph"
  | "product.sunglasses" | "product.aviator" | "product.wayfarer"
  | "product.leatherBelt" | "product.casualBelt"
  | "product.leatherWallet" | "product.cardHolder"
  | "product.necklace" | "product.earrings" | "product.bracelet"
  | "product.premium" | "product.mens" | "product.womens" | "product.tshirt" | "product.shirt" | "product.hoodie" | "product.jacket" | "product.jeans";

type Translations = Record<string, Partial<Record<TranslationKey, string>>>;

const translations: Translations = {
  en: {
    "nav.shop": "Shop",
    "nav.men": "Men",
    "nav.women": "Women",
    "nav.trending": "Trending",
    "nav.accessories": "Accessories",
    "hero.title1": "DEFINE",
    "hero.title2": "YOUR",
    "hero.title3": "FUTURE",
    "hero.description": "Discover cutting-edge fashion that transcends boundaries. Premium streetwear designed for the modern visionary.",
    "hero.explore": "Explore Collection",
    "hero.lookbook": "View Lookbook",
    "hero.trending": "Trending Now",
    "hero.views": "+10K this week",
    "categories.browse": "Browse Categories",
    "categories.title": "Shop by Category",
    "categories.products": "Products",
    "products.featured": "Curated Selection",
    "products.title": "Featured Products",
    "products.viewAll": "View All",
    "products.addToCart": "Add to Cart",
    "newsletter.title": "Join the RASU Movement",
    "newsletter.description": "Subscribe to receive exclusive offers, early access to new collections, and style inspiration.",
    "newsletter.placeholder": "Enter your email",
    "newsletter.subscribe": "Subscribe",
    "footer.description": "Redefining contemporary fashion with cutting-edge designs and sustainable practices.",
    "footer.shop": "Shop",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.legal": "Legal",
    "footer.newArrivals": "New Arrivals",
    "footer.bestsellers": "Bestsellers",
    "footer.sale": "Sale",
    "footer.collections": "Collections",
    "footer.aboutUs": "About Us",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.sustainability": "Sustainability",
    "footer.helpCenter": "Help Center",
    "footer.shipping": "Shipping",
    "footer.returns": "Returns",
    "footer.sizeGuide": "Size Guide",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    "footer.rights": "All rights reserved.",
    "footer.language": "Language",
    "cart.title": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "wishlist.title": "Your Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.new": "NEW",
    "common.sale": "SALE",
    // Categories
    "category.men": "Men",
    "category.women": "Women",
    "category.accessories": "Accessories",
    // Subcategories
    "subcategory.tshirts": "T-Shirts",
    "subcategory.shirts": "Shirts",
    "subcategory.jeans": "Jeans",
    "subcategory.trousers": "Trousers",
    "subcategory.jackets": "Jackets",
    "subcategory.hoodies": "Hoodies",
    "subcategory.shoes": "Shoes",
    "subcategory.ethnicWear": "Ethnic Wear",
    "subcategory.tops": "Tops",
    "subcategory.dresses": "Dresses",
    "subcategory.skirts": "Skirts",
    "subcategory.bags": "Bags",
    "subcategory.watches": "Watches",
    "subcategory.eyewear": "Eyewear",
    "subcategory.belts": "Belts",
    "subcategory.wallets": "Wallets",
    "subcategory.jewelry": "Jewelry",
    // Product types
    "product.premium": "Premium",
    "product.mens": "Men's",
    "product.womens": "Women's",
    "product.tshirt": "T-Shirt",
    "product.shirt": "Shirt",
    "product.hoodie": "Hoodie",
    "product.jacket": "Jacket",
    "product.jeans": "Jeans",
    "product.roundNeck": "Round Neck",
    "product.vNeck": "V-Neck",
    "product.polo": "Polo",
    "product.henley": "Henley",
    "product.graphic": "Graphic",
    "product.striped": "Striped",
    "product.solid": "Solid",
    "product.printed": "Printed",
    "product.oxford": "Oxford",
    "product.denim": "Denim",
    "product.linen": "Linen",
    "product.flannel": "Flannel",
    "product.formal": "Formal",
    "product.casual": "Casual",
    "product.slimFit": "Slim Fit",
    "product.skinny": "Skinny",
    "product.straight": "Straight",
    "product.relaxed": "Relaxed",
    "product.ripped": "Ripped",
    "product.chinos": "Chinos",
    "product.cargo": "Cargo",
    "product.joggers": "Joggers",
    "product.bomber": "Bomber",
    "product.leather": "Leather",
    "product.puffer": "Puffer",
    "product.pullover": "Pullover",
    "product.zipUp": "Zip-Up",
    "product.fleece": "Fleece",
    "product.sneakers": "Sneakers",
    "product.runningShoes": "Running Shoes",
    "product.formalShoes": "Formal Shoes",
    "product.loafers": "Loafers",
    "product.boots": "Boots",
    "product.kurta": "Kurta",
    "product.sherwani": "Sherwani",
    "product.nehruJacket": "Nehru Jacket",
    "product.cropTop": "Crop Top",
    "product.blouse": "Blouse",
    "product.tankTop": "Tank Top",
    "product.peplumTop": "Peplum Top",
    "product.wrapTop": "Wrap Top",
    "product.ruffleTop": "Ruffle Top",
    "product.maxiDress": "Maxi Dress",
    "product.midiDress": "Midi Dress",
    "product.bodycon": "Bodycon",
    "product.aLineDress": "A-Line Dress",
    "product.wrapDress": "Wrap Dress",
    "product.partyDress": "Party Dress",
    "product.momJeans": "Mom Jeans",
    "product.boyfriendJeans": "Boyfriend Jeans",
    "product.wideLeg": "Wide Leg",
    "product.palazzo": "Palazzo",
    "product.culottes": "Culottes",
    "product.cigarettePants": "Cigarette Pants",
    "product.pleatedSkirt": "Pleated Skirt",
    "product.pencilSkirt": "Pencil Skirt",
    "product.aLineSkirt": "A-Line Skirt",
    "product.denimJacket": "Denim Jacket",
    "product.blazer": "Blazer",
    "product.heels": "Heels",
    "product.sandals": "Sandals",
    "product.flats": "Flats",
    "product.saree": "Saree",
    "product.lehenga": "Lehenga",
    "product.kurti": "Kurti",
    "product.backpack": "Backpack",
    "product.toteBag": "Tote Bag",
    "product.slingBag": "Sling Bag",
    "product.duffleBag": "Duffle Bag",
    "product.analogWatch": "Analog Watch",
    "product.smartWatch": "Smart Watch",
    "product.chronograph": "Chronograph",
    "product.sunglasses": "Sunglasses",
    "product.aviator": "Aviator",
    "product.wayfarer": "Wayfarer",
    "product.leatherBelt": "Leather Belt",
    "product.casualBelt": "Casual Belt",
    "product.leatherWallet": "Leather Wallet",
    "product.cardHolder": "Card Holder",
    "product.necklace": "Necklace",
    "product.earrings": "Earrings",
    "product.bracelet": "Bracelet",
  },
  hi: {
    "nav.shop": "खरीदारी",
    "nav.men": "पुरुष",
    "nav.women": "महिला",
    "nav.trending": "ट्रेंडिंग",
    "nav.accessories": "एक्सेसरीज़",
    "hero.title1": "परिभाषित",
    "hero.title2": "अपना",
    "hero.title3": "भविष्य",
    "hero.description": "सीमाओं को पार करने वाले अत्याधुनिक फैशन की खोज करें। आधुनिक दूरदर्शी के लिए डिज़ाइन किया गया प्रीमियम स्ट्रीटवियर।",
    "hero.explore": "कलेक्शन देखें",
    "hero.lookbook": "लुकबुक देखें",
    "hero.trending": "ट्रेंडिंग अभी",
    "hero.views": "+10K इस सप्ताह",
    "categories.browse": "श्रेणियां ब्राउज़ करें",
    "categories.title": "श्रेणी के अनुसार खरीदें",
    "categories.products": "उत्पाद",
    "products.featured": "क्यूरेटेड सेलेक्शन",
    "products.title": "फीचर्ड प्रोडक्ट्स",
    "products.viewAll": "सभी देखें",
    "products.addToCart": "कार्ट में डालें",
    "newsletter.title": "RASU मूवमेंट में शामिल हों",
    "newsletter.description": "विशेष ऑफ़र, नए कलेक्शन की पहली पहुंच और स्टाइल इंस्पिरेशन प्राप्त करें।",
    "newsletter.placeholder": "अपना ईमेल दर्ज करें",
    "newsletter.subscribe": "सब्सक्राइब करें",
    "footer.description": "अत्याधुनिक डिज़ाइन और टिकाऊ प्रथाओं के साथ समकालीन फैशन को फिर से परिभाषित करना।",
    "footer.shop": "खरीदारी",
    "footer.company": "कंपनी",
    "footer.support": "सहायता",
    "footer.legal": "कानूनी",
    "footer.newArrivals": "नए आगमन",
    "footer.bestsellers": "बेस्टसेलर",
    "footer.sale": "सेल",
    "footer.collections": "कलेक्शन",
    "footer.aboutUs": "हमारे बारे में",
    "footer.careers": "करियर",
    "footer.press": "प्रेस",
    "footer.sustainability": "स्थिरता",
    "footer.helpCenter": "सहायता केंद्र",
    "footer.shipping": "शिपिंग",
    "footer.returns": "रिटर्न",
    "footer.sizeGuide": "साइज़ गाइड",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "सेवा की शर्तें",
    "footer.cookies": "कुकी नीति",
    "footer.rights": "सर्वाधिकार सुरक्षित।",
    "footer.language": "भाषा",
    "cart.title": "आपकी कार्ट",
    "cart.empty": "आपकी कार्ट खाली है",
    "cart.total": "कुल",
    "cart.checkout": "चेकआउट",
    "wishlist.title": "आपकी विशलिस्ट",
    "wishlist.empty": "आपकी विशलिस्ट खाली है",
    "common.search": "खोजें",
    "common.loading": "लोड हो रहा है...",
    "common.new": "नया",
    "common.sale": "सेल",
    // Categories
    "category.men": "पुरुष",
    "category.women": "महिला",
    "category.accessories": "एक्सेसरीज़",
    // Subcategories
    "subcategory.tshirts": "टी-शर्ट",
    "subcategory.shirts": "शर्ट",
    "subcategory.jeans": "जींस",
    "subcategory.trousers": "ट्राउज़र",
    "subcategory.jackets": "जैकेट",
    "subcategory.hoodies": "हुडी",
    "subcategory.shoes": "जूते",
    "subcategory.ethnicWear": "एथनिक वियर",
    "subcategory.tops": "टॉप्स",
    "subcategory.dresses": "ड्रेस",
    "subcategory.skirts": "स्कर्ट",
    "subcategory.bags": "बैग",
    "subcategory.watches": "घड़ियाँ",
    "subcategory.eyewear": "ऐनक",
    "subcategory.belts": "बेल्ट",
    "subcategory.wallets": "वॉलेट",
    "subcategory.jewelry": "आभूषण",
    // Product types
    "product.premium": "प्रीमियम",
    "product.mens": "पुरुषों का",
    "product.womens": "महिलाओं का",
    "product.tshirt": "टी-शर्ट",
    "product.shirt": "शर्ट",
    "product.hoodie": "हुडी",
    "product.jacket": "जैकेट",
    "product.jeans": "जींस",
    "product.roundNeck": "राउंड नेक",
    "product.vNeck": "वी-नेक",
    "product.polo": "पोलो",
    "product.henley": "हेनले",
    "product.graphic": "ग्राफिक",
    "product.striped": "धारीदार",
    "product.solid": "सॉलिड",
    "product.printed": "प्रिंटेड",
    "product.oxford": "ऑक्सफोर्ड",
    "product.denim": "डेनिम",
    "product.linen": "लिनन",
    "product.flannel": "फ्लैनल",
    "product.formal": "फॉर्मल",
    "product.casual": "कैजुअल",
    "product.slimFit": "स्लिम फिट",
    "product.skinny": "स्किनी",
    "product.straight": "स्ट्रेट",
    "product.relaxed": "रिलैक्स्ड",
    "product.ripped": "रिप्ड",
    "product.chinos": "चिनोस",
    "product.cargo": "कार्गो",
    "product.joggers": "जॉगर्स",
    "product.bomber": "बॉम्बर",
    "product.leather": "लेदर",
    "product.puffer": "पफर",
    "product.pullover": "पुलओवर",
    "product.zipUp": "ज़िप-अप",
    "product.fleece": "फ्लीस",
    "product.sneakers": "स्नीकर्स",
    "product.runningShoes": "रनिंग शूज़",
    "product.formalShoes": "फॉर्मल शूज़",
    "product.loafers": "लोफर्स",
    "product.boots": "बूट्स",
    "product.kurta": "कुर्ता",
    "product.sherwani": "शेरवानी",
    "product.nehruJacket": "नेहरू जैकेट",
    "product.cropTop": "क्रॉप टॉप",
    "product.blouse": "ब्लाउज",
    "product.tankTop": "टैंक टॉप",
    "product.peplumTop": "पेप्लम टॉप",
    "product.wrapTop": "रैप टॉप",
    "product.ruffleTop": "रफल टॉप",
    "product.maxiDress": "मैक्सी ड्रेस",
    "product.midiDress": "मिडी ड्रेस",
    "product.bodycon": "बॉडीकॉन",
    "product.aLineDress": "ए-लाइन ड्रेस",
    "product.wrapDress": "रैप ड्रेस",
    "product.partyDress": "पार्टी ड्रेस",
    "product.momJeans": "मॉम जींस",
    "product.boyfriendJeans": "बॉयफ्रेंड जींस",
    "product.wideLeg": "वाइड लेग",
    "product.palazzo": "पलाज़ो",
    "product.culottes": "क्यूलोट्स",
    "product.cigarettePants": "सिगरेट पैंट्स",
    "product.pleatedSkirt": "प्लीटेड स्कर्ट",
    "product.pencilSkirt": "पेंसिल स्कर्ट",
    "product.aLineSkirt": "ए-लाइन स्कर्ट",
    "product.denimJacket": "डेनिम जैकेट",
    "product.blazer": "ब्लेज़र",
    "product.heels": "हील्स",
    "product.sandals": "सैंडल",
    "product.flats": "फ्लैट्स",
    "product.saree": "साड़ी",
    "product.lehenga": "लहंगा",
    "product.kurti": "कुर्ती",
    "product.backpack": "बैकपैक",
    "product.toteBag": "टोट बैग",
    "product.slingBag": "स्लिंग बैग",
    "product.duffleBag": "डफल बैग",
    "product.analogWatch": "एनालॉग घड़ी",
    "product.smartWatch": "स्मार्ट वॉच",
    "product.chronograph": "क्रोनोग्राफ",
    "product.sunglasses": "सनग्लासेस",
    "product.aviator": "एविएटर",
    "product.wayfarer": "वेफेयरर",
    "product.leatherBelt": "लेदर बेल्ट",
    "product.casualBelt": "कैजुअल बेल्ट",
    "product.leatherWallet": "लेदर वॉलेट",
    "product.cardHolder": "कार्ड होल्डर",
    "product.necklace": "हार",
    "product.earrings": "झुमके",
    "product.bracelet": "ब्रेसलेट",
  },
  es: {
    "nav.shop": "Tienda",
    "nav.men": "Hombre",
    "nav.women": "Mujer",
    "nav.trending": "Tendencias",
    "nav.accessories": "Accesorios",
    "hero.title1": "DEFINE",
    "hero.title2": "TU",
    "hero.title3": "FUTURO",
    "hero.description": "Descubre moda vanguardista que trasciende fronteras. Ropa urbana premium diseñada para el visionario moderno.",
    "hero.explore": "Explorar Colección",
    "hero.lookbook": "Ver Lookbook",
    "hero.trending": "Tendencias Ahora",
    "hero.views": "+10K esta semana",
    "categories.browse": "Explorar Categorías",
    "categories.title": "Comprar por Categoría",
    "categories.products": "Productos",
    "products.featured": "Selección Curada",
    "products.title": "Productos Destacados",
    "products.viewAll": "Ver Todo",
    "products.addToCart": "Añadir al Carrito",
    "newsletter.title": "Únete al Movimiento RASU",
    "newsletter.description": "Suscríbete para recibir ofertas exclusivas, acceso anticipado a nuevas colecciones e inspiración de estilo.",
    "newsletter.placeholder": "Ingresa tu email",
    "newsletter.subscribe": "Suscribirse",
    "footer.description": "Redefiniendo la moda contemporánea con diseños vanguardistas y prácticas sostenibles.",
    "footer.shop": "Tienda",
    "footer.company": "Empresa",
    "footer.support": "Soporte",
    "footer.legal": "Legal",
    "footer.newArrivals": "Novedades",
    "footer.bestsellers": "Más Vendidos",
    "footer.sale": "Ofertas",
    "footer.collections": "Colecciones",
    "footer.aboutUs": "Sobre Nosotros",
    "footer.careers": "Carreras",
    "footer.press": "Prensa",
    "footer.sustainability": "Sostenibilidad",
    "footer.helpCenter": "Centro de Ayuda",
    "footer.shipping": "Envío",
    "footer.returns": "Devoluciones",
    "footer.sizeGuide": "Guía de Tallas",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.cookies": "Política de Cookies",
    "footer.rights": "Todos los derechos reservados.",
    "footer.language": "Idioma",
    "cart.title": "Tu Carrito",
    "cart.empty": "Tu carrito está vacío",
    "cart.total": "Total",
    "cart.checkout": "Pagar",
    "wishlist.title": "Tu Lista de Deseos",
    "wishlist.empty": "Tu lista de deseos está vacía",
    "common.search": "Buscar",
    "common.loading": "Cargando...",
    "common.new": "NUEVO",
    "common.sale": "OFERTA",
    // Categories
    "category.men": "Hombre",
    "category.women": "Mujer",
    "category.accessories": "Accesorios",
    // Subcategories
    "subcategory.tshirts": "Camisetas",
    "subcategory.shirts": "Camisas",
    "subcategory.jeans": "Jeans",
    "subcategory.trousers": "Pantalones",
    "subcategory.jackets": "Chaquetas",
    "subcategory.hoodies": "Sudaderas",
    "subcategory.shoes": "Zapatos",
    "subcategory.ethnicWear": "Ropa Étnica",
    "subcategory.tops": "Blusas",
    "subcategory.dresses": "Vestidos",
    "subcategory.skirts": "Faldas",
    "subcategory.bags": "Bolsos",
    "subcategory.watches": "Relojes",
    "subcategory.eyewear": "Gafas",
    "subcategory.belts": "Cinturones",
    "subcategory.wallets": "Carteras",
    "subcategory.jewelry": "Joyería",
    // Product types
    "product.premium": "Premium",
    "product.mens": "Hombre",
    "product.womens": "Mujer",
    "product.tshirt": "Camiseta",
    "product.shirt": "Camisa",
    "product.hoodie": "Sudadera",
    "product.jacket": "Chaqueta",
    "product.jeans": "Jeans",
    "product.roundNeck": "Cuello Redondo",
    "product.vNeck": "Cuello V",
    "product.polo": "Polo",
    "product.henley": "Henley",
    "product.graphic": "Gráfica",
    "product.striped": "Rayada",
    "product.solid": "Sólida",
    "product.printed": "Estampada",
    "product.oxford": "Oxford",
    "product.denim": "Mezclilla",
    "product.linen": "Lino",
    "product.flannel": "Franela",
    "product.formal": "Formal",
    "product.casual": "Casual",
    "product.slimFit": "Ajustado",
    "product.skinny": "Skinny",
    "product.straight": "Recto",
    "product.relaxed": "Holgado",
    "product.ripped": "Rasgado",
    "product.chinos": "Chinos",
    "product.cargo": "Cargo",
    "product.joggers": "Joggers",
    "product.bomber": "Bomber",
    "product.leather": "Cuero",
    "product.puffer": "Acolchada",
    "product.pullover": "Pullover",
    "product.zipUp": "Con Cremallera",
    "product.fleece": "Polar",
    "product.sneakers": "Zapatillas",
    "product.runningShoes": "Zapatillas Running",
    "product.formalShoes": "Zapatos Formales",
    "product.loafers": "Mocasines",
    "product.boots": "Botas",
    "product.kurta": "Kurta",
    "product.sherwani": "Sherwani",
    "product.nehruJacket": "Chaqueta Nehru",
    "product.cropTop": "Crop Top",
    "product.blouse": "Blusa",
    "product.tankTop": "Camiseta Tirantes",
    "product.peplumTop": "Blusa Peplum",
    "product.wrapTop": "Blusa Cruzada",
    "product.ruffleTop": "Blusa Volantes",
    "product.maxiDress": "Vestido Largo",
    "product.midiDress": "Vestido Midi",
    "product.bodycon": "Vestido Entallado",
    "product.aLineDress": "Vestido Línea A",
    "product.wrapDress": "Vestido Cruzado",
    "product.partyDress": "Vestido Fiesta",
    "product.momJeans": "Mom Jeans",
    "product.boyfriendJeans": "Boyfriend Jeans",
    "product.wideLeg": "Pierna Ancha",
    "product.palazzo": "Palazzo",
    "product.culottes": "Culottes",
    "product.cigarettePants": "Pantalón Cigarette",
    "product.pleatedSkirt": "Falda Plisada",
    "product.pencilSkirt": "Falda Lápiz",
    "product.aLineSkirt": "Falda Línea A",
    "product.denimJacket": "Chaqueta Mezclilla",
    "product.blazer": "Blazer",
    "product.heels": "Tacones",
    "product.sandals": "Sandalias",
    "product.flats": "Zapatos Planos",
    "product.saree": "Sari",
    "product.lehenga": "Lehenga",
    "product.kurti": "Kurti",
    "product.backpack": "Mochila",
    "product.toteBag": "Bolso Tote",
    "product.slingBag": "Bolso Bandolera",
    "product.duffleBag": "Bolsa Deportiva",
    "product.analogWatch": "Reloj Analógico",
    "product.smartWatch": "Reloj Inteligente",
    "product.chronograph": "Cronógrafo",
    "product.sunglasses": "Gafas de Sol",
    "product.aviator": "Aviador",
    "product.wayfarer": "Wayfarer",
    "product.leatherBelt": "Cinturón Cuero",
    "product.casualBelt": "Cinturón Casual",
    "product.leatherWallet": "Cartera Cuero",
    "product.cardHolder": "Tarjetero",
    "product.necklace": "Collar",
    "product.earrings": "Pendientes",
    "product.bracelet": "Pulsera",
  },
  fr: {
    "nav.shop": "Boutique",
    "nav.men": "Homme",
    "nav.women": "Femme",
    "nav.trending": "Tendances",
    "nav.accessories": "Accessoires",
    "hero.title1": "DÉFINISSEZ",
    "hero.title2": "VOTRE",
    "hero.title3": "FUTUR",
    "hero.description": "Découvrez une mode avant-gardiste qui transcende les frontières. Streetwear premium conçu pour le visionnaire moderne.",
    "hero.explore": "Explorer la Collection",
    "hero.lookbook": "Voir le Lookbook",
    "hero.trending": "Tendances Maintenant",
    "hero.views": "+10K cette semaine",
    "categories.browse": "Parcourir les Catégories",
    "categories.title": "Acheter par Catégorie",
    "categories.products": "Produits",
    "products.featured": "Sélection Curatée",
    "products.title": "Produits Vedettes",
    "products.viewAll": "Voir Tout",
    "products.addToCart": "Ajouter au Panier",
    "newsletter.title": "Rejoignez le Mouvement RASU",
    "newsletter.description": "Abonnez-vous pour recevoir des offres exclusives, un accès anticipé aux nouvelles collections et de l'inspiration style.",
    "newsletter.placeholder": "Entrez votre email",
    "newsletter.subscribe": "S'abonner",
    "footer.description": "Redéfinir la mode contemporaine avec des designs avant-gardistes et des pratiques durables.",
    "footer.shop": "Boutique",
    "footer.company": "Entreprise",
    "footer.support": "Support",
    "footer.legal": "Légal",
    "footer.newArrivals": "Nouveautés",
    "footer.bestsellers": "Meilleures Ventes",
    "footer.sale": "Soldes",
    "footer.collections": "Collections",
    "footer.aboutUs": "À Propos",
    "footer.careers": "Carrières",
    "footer.press": "Presse",
    "footer.sustainability": "Durabilité",
    "footer.helpCenter": "Centre d'Aide",
    "footer.shipping": "Livraison",
    "footer.returns": "Retours",
    "footer.sizeGuide": "Guide des Tailles",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.cookies": "Politique de Cookies",
    "footer.rights": "Tous droits réservés.",
    "footer.language": "Langue",
    "cart.title": "Votre Panier",
    "cart.empty": "Votre panier est vide",
    "cart.total": "Total",
    "cart.checkout": "Paiement",
    "wishlist.title": "Votre Liste de Souhaits",
    "wishlist.empty": "Votre liste de souhaits est vide",
    "common.search": "Rechercher",
    "common.loading": "Chargement...",
    "common.new": "NOUVEAU",
    "common.sale": "SOLDES",
    // Categories
    "category.men": "Homme",
    "category.women": "Femme",
    "category.accessories": "Accessoires",
    // Subcategories
    "subcategory.tshirts": "T-Shirts",
    "subcategory.shirts": "Chemises",
    "subcategory.jeans": "Jeans",
    "subcategory.trousers": "Pantalons",
    "subcategory.jackets": "Vestes",
    "subcategory.hoodies": "Sweats",
    "subcategory.shoes": "Chaussures",
    "subcategory.ethnicWear": "Tenue Ethnique",
    "subcategory.tops": "Hauts",
    "subcategory.dresses": "Robes",
    "subcategory.skirts": "Jupes",
    "subcategory.bags": "Sacs",
    "subcategory.watches": "Montres",
    "subcategory.eyewear": "Lunettes",
    "subcategory.belts": "Ceintures",
    "subcategory.wallets": "Portefeuilles",
    "subcategory.jewelry": "Bijoux",
    // Product types
    "product.premium": "Premium",
    "product.mens": "Homme",
    "product.womens": "Femme",
    "product.tshirt": "T-Shirt",
    "product.shirt": "Chemise",
    "product.hoodie": "Sweat",
    "product.jacket": "Veste",
    "product.jeans": "Jean",
    "product.roundNeck": "Col Rond",
    "product.vNeck": "Col V",
    "product.polo": "Polo",
    "product.henley": "Henley",
    "product.graphic": "Graphique",
    "product.striped": "Rayé",
    "product.solid": "Uni",
    "product.printed": "Imprimé",
    "product.oxford": "Oxford",
    "product.denim": "Denim",
    "product.linen": "Lin",
    "product.flannel": "Flanelle",
    "product.formal": "Formel",
    "product.casual": "Décontracté",
    "product.slimFit": "Coupe Slim",
    "product.skinny": "Skinny",
    "product.straight": "Droit",
    "product.relaxed": "Détendu",
    "product.ripped": "Déchiré",
    "product.chinos": "Chinos",
    "product.cargo": "Cargo",
    "product.joggers": "Joggers",
    "product.bomber": "Bomber",
    "product.leather": "Cuir",
    "product.puffer": "Doudoune",
    "product.pullover": "Pull",
    "product.zipUp": "Zippé",
    "product.fleece": "Polaire",
    "product.sneakers": "Baskets",
    "product.runningShoes": "Chaussures Running",
    "product.formalShoes": "Chaussures Habillées",
    "product.loafers": "Mocassins",
    "product.boots": "Bottes",
    "product.kurta": "Kurta",
    "product.sherwani": "Sherwani",
    "product.nehruJacket": "Veste Nehru",
    "product.cropTop": "Crop Top",
    "product.blouse": "Blouse",
    "product.tankTop": "Débardeur",
    "product.peplumTop": "Haut Peplum",
    "product.wrapTop": "Haut Cache-Coeur",
    "product.ruffleTop": "Haut à Volants",
    "product.maxiDress": "Robe Longue",
    "product.midiDress": "Robe Midi",
    "product.bodycon": "Robe Moulante",
    "product.aLineDress": "Robe Ligne A",
    "product.wrapDress": "Robe Portefeuille",
    "product.partyDress": "Robe de Soirée",
    "product.momJeans": "Mom Jeans",
    "product.boyfriendJeans": "Boyfriend Jeans",
    "product.wideLeg": "Jambe Large",
    "product.palazzo": "Palazzo",
    "product.culottes": "Culottes",
    "product.cigarettePants": "Pantalon Cigarette",
    "product.pleatedSkirt": "Jupe Plissée",
    "product.pencilSkirt": "Jupe Crayon",
    "product.aLineSkirt": "Jupe Ligne A",
    "product.denimJacket": "Veste en Jean",
    "product.blazer": "Blazer",
    "product.heels": "Talons",
    "product.sandals": "Sandales",
    "product.flats": "Ballerines",
    "product.saree": "Sari",
    "product.lehenga": "Lehenga",
    "product.kurti": "Kurti",
    "product.backpack": "Sac à Dos",
    "product.toteBag": "Sac Cabas",
    "product.slingBag": "Sac Bandoulière",
    "product.duffleBag": "Sac de Sport",
    "product.analogWatch": "Montre Analogique",
    "product.smartWatch": "Montre Connectée",
    "product.chronograph": "Chronographe",
    "product.sunglasses": "Lunettes de Soleil",
    "product.aviator": "Aviateur",
    "product.wayfarer": "Wayfarer",
    "product.leatherBelt": "Ceinture Cuir",
    "product.casualBelt": "Ceinture Décontractée",
    "product.leatherWallet": "Portefeuille Cuir",
    "product.cardHolder": "Porte-Cartes",
    "product.necklace": "Collier",
    "product.earrings": "Boucles d'Oreilles",
    "product.bracelet": "Bracelet",
  },
  de: {
    "nav.shop": "Shop",
    "nav.men": "Herren",
    "nav.women": "Damen",
    "nav.trending": "Trends",
    "nav.accessories": "Accessoires",
    "hero.title1": "DEFINIERE",
    "hero.title2": "DEINE",
    "hero.title3": "ZUKUNFT",
    "hero.description": "Entdecke hochmoderne Mode, die Grenzen überschreitet. Premium Streetwear für den modernen Visionär.",
    "hero.explore": "Kollektion Entdecken",
    "hero.lookbook": "Lookbook Ansehen",
    "hero.trending": "Jetzt im Trend",
    "hero.views": "+10K diese Woche",
    "categories.browse": "Kategorien Durchsuchen",
    "categories.title": "Nach Kategorie Kaufen",
    "categories.products": "Produkte",
    "products.featured": "Kuratierte Auswahl",
    "products.title": "Ausgewählte Produkte",
    "products.viewAll": "Alle Ansehen",
    "products.addToCart": "In den Warenkorb",
    "newsletter.title": "Werde Teil der RASU Bewegung",
    "newsletter.description": "Abonniere für exklusive Angebote, frühen Zugang zu neuen Kollektionen und Stil-Inspiration.",
    "newsletter.placeholder": "E-Mail eingeben",
    "newsletter.subscribe": "Abonnieren",
    "footer.description": "Zeitgenössische Mode mit innovativen Designs und nachhaltigen Praktiken neu definieren.",
    "footer.shop": "Shop",
    "footer.company": "Unternehmen",
    "footer.support": "Support",
    "footer.legal": "Rechtliches",
    "footer.newArrivals": "Neuheiten",
    "footer.bestsellers": "Bestseller",
    "footer.sale": "Sale",
    "footer.collections": "Kollektionen",
    "footer.aboutUs": "Über Uns",
    "footer.careers": "Karriere",
    "footer.press": "Presse",
    "footer.sustainability": "Nachhaltigkeit",
    "footer.helpCenter": "Hilfe-Center",
    "footer.shipping": "Versand",
    "footer.returns": "Rückgabe",
    "footer.sizeGuide": "Größentabelle",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "footer.cookies": "Cookie-Richtlinie",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.language": "Sprache",
    "cart.title": "Dein Warenkorb",
    "cart.empty": "Dein Warenkorb ist leer",
    "cart.total": "Gesamt",
    "cart.checkout": "Zur Kasse",
    "wishlist.title": "Deine Wunschliste",
    "wishlist.empty": "Deine Wunschliste ist leer",
    "common.search": "Suchen",
    "common.loading": "Laden...",
    "common.new": "NEU",
    "common.sale": "SALE",
    // Categories
    "category.men": "Herren",
    "category.women": "Damen",
    "category.accessories": "Accessoires",
    // Subcategories
    "subcategory.tshirts": "T-Shirts",
    "subcategory.shirts": "Hemden",
    "subcategory.jeans": "Jeans",
    "subcategory.trousers": "Hosen",
    "subcategory.jackets": "Jacken",
    "subcategory.hoodies": "Kapuzenpullover",
    "subcategory.shoes": "Schuhe",
    "subcategory.ethnicWear": "Ethnische Kleidung",
    "subcategory.tops": "Oberteile",
    "subcategory.dresses": "Kleider",
    "subcategory.skirts": "Röcke",
    "subcategory.bags": "Taschen",
    "subcategory.watches": "Uhren",
    "subcategory.eyewear": "Brillen",
    "subcategory.belts": "Gürtel",
    "subcategory.wallets": "Geldbörsen",
    "subcategory.jewelry": "Schmuck",
    // Product types
    "product.premium": "Premium",
    "product.mens": "Herren",
    "product.womens": "Damen",
    "product.tshirt": "T-Shirt",
    "product.shirt": "Hemd",
    "product.hoodie": "Kapuzenpullover",
    "product.jacket": "Jacke",
    "product.jeans": "Jeans",
    "product.roundNeck": "Rundhals",
    "product.vNeck": "V-Ausschnitt",
    "product.polo": "Polo",
    "product.henley": "Henley",
    "product.graphic": "Grafik",
    "product.striped": "Gestreift",
    "product.solid": "Unifarben",
    "product.printed": "Bedruckt",
    "product.oxford": "Oxford",
    "product.denim": "Denim",
    "product.linen": "Leinen",
    "product.flannel": "Flanell",
    "product.formal": "Formell",
    "product.casual": "Lässig",
    "product.slimFit": "Slim Fit",
    "product.skinny": "Skinny",
    "product.straight": "Gerade",
    "product.relaxed": "Entspannt",
    "product.ripped": "Zerrissen",
    "product.chinos": "Chinos",
    "product.cargo": "Cargo",
    "product.joggers": "Jogginghosen",
    "product.bomber": "Bomber",
    "product.leather": "Leder",
    "product.puffer": "Steppjacke",
    "product.pullover": "Pullover",
    "product.zipUp": "Mit Reißverschluss",
    "product.fleece": "Fleece",
    "product.sneakers": "Sneaker",
    "product.runningShoes": "Laufschuhe",
    "product.formalShoes": "Formelle Schuhe",
    "product.loafers": "Loafer",
    "product.boots": "Stiefel",
    "product.kurta": "Kurta",
    "product.sherwani": "Sherwani",
    "product.nehruJacket": "Nehru-Jacke",
    "product.cropTop": "Crop Top",
    "product.blouse": "Bluse",
    "product.tankTop": "Tanktop",
    "product.peplumTop": "Peplum Top",
    "product.wrapTop": "Wickeloberteil",
    "product.ruffleTop": "Rüschenoberteil",
    "product.maxiDress": "Maxikleid",
    "product.midiDress": "Midikleid",
    "product.bodycon": "Figurbetontes Kleid",
    "product.aLineDress": "A-Linien-Kleid",
    "product.wrapDress": "Wickelkleid",
    "product.partyDress": "Partykleid",
    "product.momJeans": "Mom Jeans",
    "product.boyfriendJeans": "Boyfriend Jeans",
    "product.wideLeg": "Weites Bein",
    "product.palazzo": "Palazzo",
    "product.culottes": "Culottes",
    "product.cigarettePants": "Zigarettenhose",
    "product.pleatedSkirt": "Faltenrock",
    "product.pencilSkirt": "Bleistiftrock",
    "product.aLineSkirt": "A-Linien-Rock",
    "product.denimJacket": "Jeansjacke",
    "product.blazer": "Blazer",
    "product.heels": "Absätze",
    "product.sandals": "Sandalen",
    "product.flats": "Flache Schuhe",
    "product.saree": "Sari",
    "product.lehenga": "Lehenga",
    "product.kurti": "Kurti",
    "product.backpack": "Rucksack",
    "product.toteBag": "Tragetasche",
    "product.slingBag": "Umhängetasche",
    "product.duffleBag": "Sporttasche",
    "product.analogWatch": "Analoguhr",
    "product.smartWatch": "Smartwatch",
    "product.chronograph": "Chronograph",
    "product.sunglasses": "Sonnenbrille",
    "product.aviator": "Flieger",
    "product.wayfarer": "Wayfarer",
    "product.leatherBelt": "Ledergürtel",
    "product.casualBelt": "Freizeitgürtel",
    "product.leatherWallet": "Ledergeldbörse",
    "product.cardHolder": "Kartenhalter",
    "product.necklace": "Halskette",
    "product.earrings": "Ohrringe",
    "product.bracelet": "Armband",
  },
};

// Default fallback to English for missing translations
const getTranslation = (lang: string, key: TranslationKey): string => {
  return translations[lang]?.[key] || translations.en[key] || key;
};

// Product name translation mapping
const productNameMap: Record<string, TranslationKey> = {
  "Round Neck": "product.roundNeck", "V-Neck": "product.vNeck", "Polo": "product.polo",
  "Henley": "product.henley", "Graphic": "product.graphic", "Striped": "product.striped",
  "Solid": "product.solid", "Printed": "product.printed", "Oxford": "product.oxford",
  "Denim": "product.denim", "Linen": "product.linen", "Flannel": "product.flannel",
  "Formal": "product.formal", "Casual": "product.casual", "Slim Fit": "product.slimFit",
  "Skinny": "product.skinny", "Straight": "product.straight", "Relaxed": "product.relaxed",
  "Ripped": "product.ripped", "Chinos": "product.chinos", "Cargo": "product.cargo",
  "Joggers": "product.joggers", "Bomber": "product.bomber", "Leather": "product.leather",
  "Puffer": "product.puffer", "Pullover": "product.pullover", "Zip-Up": "product.zipUp",
  "Fleece": "product.fleece", "Sneakers": "product.sneakers", "Running Shoes": "product.runningShoes",
  "Formal Shoes": "product.formalShoes", "Loafers": "product.loafers", "Boots": "product.boots",
  "Kurta": "product.kurta", "Sherwani": "product.sherwani", "Nehru Jacket": "product.nehruJacket",
  "Crop Top": "product.cropTop", "Blouse": "product.blouse", "Tank Top": "product.tankTop",
  "Peplum Top": "product.peplumTop", "Wrap Top": "product.wrapTop", "Ruffle Top": "product.ruffleTop",
  "Maxi Dress": "product.maxiDress", "Midi Dress": "product.midiDress", "Bodycon": "product.bodycon",
  "A-Line Dress": "product.aLineDress", "Wrap Dress": "product.wrapDress", "Party Dress": "product.partyDress",
  "Mom": "product.momJeans", "Boyfriend": "product.boyfriendJeans", "Wide Leg": "product.wideLeg",
  "Palazzo": "product.palazzo", "Culottes": "product.culottes", "Cigarette Pants": "product.cigarettePants",
  "Pleated Skirt": "product.pleatedSkirt", "Pencil Skirt": "product.pencilSkirt", "A-Line Skirt": "product.aLineSkirt",
  "Denim Jacket": "product.denimJacket", "Leather Jacket": "product.leather", "Blazer": "product.blazer",
  "Heels": "product.heels", "Sandals": "product.sandals", "Flats": "product.flats",
  "Saree": "product.saree", "Lehenga": "product.lehenga", "Kurti": "product.kurti",
  "Backpack": "product.backpack", "Tote Bag": "product.toteBag", "Sling Bag": "product.slingBag",
  "Duffle Bag": "product.duffleBag", "Analog Watch": "product.analogWatch", "Smart Watch": "product.smartWatch",
  "Chronograph": "product.chronograph", "Sunglasses": "product.sunglasses", "Aviator": "product.aviator",
  "Wayfarer": "product.wayfarer", "Leather Belt": "product.leatherBelt", "Casual Belt": "product.casualBelt",
  "Leather Wallet": "product.leatherWallet", "Card Holder": "product.cardHolder",
  "Necklace": "product.necklace", "Earrings": "product.earrings", "Bracelet": "product.bracelet",
  "Premium": "product.premium", "T-Shirt": "product.tshirt", "Shirt": "product.shirt",
  "Hoodie": "product.hoodie", "Jacket": "product.jacket", "Jeans": "product.jeans",
  "Trousers": "product.formal", "Men's": "product.mens", "Women's": "product.womens",
};

export const translateProductName = (name: string, t: (key: TranslationKey) => string): string => {
  let translatedName = name;
  for (const [english, key] of Object.entries(productNameMap)) {
    if (translatedName.includes(english)) {
      translatedName = translatedName.replace(english, t(key));
    }
  }
  return translatedName;
};

export const translateCategory = (category: string, t: (key: TranslationKey) => string): string => {
  const categoryMap: Record<string, TranslationKey> = {
    "men": "category.men", "women": "category.women", "accessories": "category.accessories"
  };
  return categoryMap[category.toLowerCase()] ? t(categoryMap[category.toLowerCase()]) : category;
};

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("preferred-language");
    if (saved) {
      const found = languages.find(l => l.code === saved);
      if (found) return found;
    }
    return languages[0]; // Default to English
  });

  useEffect(() => {
    localStorage.setItem("preferred-language", currentLanguage.code);
    document.documentElement.lang = currentLanguage.code;
    // Set text direction for RTL languages
    document.documentElement.dir = currentLanguage.code === "ar" ? "rtl" : "ltr";
  }, [currentLanguage]);

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    // Sync with react-i18next so all t() translations update globally
    i18n.changeLanguage(lang.code);
    localStorage.setItem('rasu_language', lang.code);
  };

  const t = (key: TranslationKey): string => {
    return getTranslation(currentLanguage.code, key);
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
